sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install ."
  - "pip install coverage coveralls"
  - "rm -rf picogeojson"
script: "coverage run --source=picogeojson tests/tests.py && coverage report"
after_success: "coveralls"
