sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  #- "pypy3"
env:
  - PICOGEOJSON_PYJSON=0
  - PICOGEOJSON_PYJSON=1
matrix:
  exclude:
    - python: "pypy"
      env: PICOGEOJSON_PYJSON=0
before_install:
  - if [[ "$PICOGEOJSON_PYJSON" == "0" ]]; then pip install ujson; fi
install:
  - "pip install ."
  - "pip install coverage coveralls"
  - "rm -rf picogeojson"
script: "coverage run --source=picogeojson tests/tests.py && coverage report"
after_success: "coveralls"
